//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        public int ID { get; set; }
        [Display(Name = "Tên tài khoản")]

        public string NAMEUSER { get; set; }

        public string ROLEUSER { get; set; }
        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được trống")]
        [DataType(DataType.Password)]
        public string PASSWORDUSER { get; set; }

        [NotMapped]
        [Compare("PASSWORDUSER")]
        [DisplayName("Nhập lại mật khẩu")]
        public string confirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }

    }
}
