//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }

        public int PRODUCTID { get; set; }
        [Display(Name = "Tên Sản Phẩm")]
        [Required(ErrorMessage = "*")]
        public string TENSP { get; set; }
        [Display(Name = "Mô Tả Sản Phẩm")]
        [Required(ErrorMessage = "*")]
        public string MOTASP { get; set; }
        public string MADANHMUC { get; set; }
        [Display(Name = "Giá Sản Phẩm")]
        [Required(ErrorMessage = "*")]
        public Nullable<decimal> GIASP { get; set; }
        [Display(Name = "Hình Ảnh Sản Phẩm")]
        [Required(ErrorMessage = "*")]
        public string HINHANHSP { get; set; }
        [Display(Name = "Số Lượng Sản Phẩm")]
        [Required(ErrorMessage = "*")]
        public int SOLUONG { get; set; }


        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual CHITIETDONHANG CHITIETDONHANG { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }

    }
}
