//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER
    {
        public int IDVOUCHER { get; set; }
        public string TENVOUCHER { get; set; }
        public Nullable<double> CHIETKHAU { get; set; }
    }
}
